#!/usr/bin/env python3
"""Generate a server-side FiveM graphics pack resource built on timecycle modifiers.

Usage:
    python make_timecycle_pack.py --name dio_gfx -o ./dio_gfx
    python make_timecycle_pack.py --name dio_gfx --looks warm,cinematic --default warm --no-tiers -o ./dio_gfx

Output:
    <out>/fxmanifest.lua
    <out>/data/timecycle_mods_<name>.xml   (registered with data_file 'TIMECYCLEMOD_FILE')
    <out>/client.lua                       (/graphics command, per-player choice saved with KVP,
                                            applied in the EXTRA timecycle slot so the primary
                                            slot stays free for gameplay effects)
    <out>/README.md

Format follows FiveM's own TimeCycle Editor "Generate XML" output
(<modifier name numMods userFlags><var_name>value1 value2</var_name>); the first
value is the one that applies. Look values and tier values are rules of thumb to
tune in game with the TimeCycle Editor (sv_pureLevel 0 on a dev server), not
measured standards. Standard library only.
"""
import argparse
import os

# Only post-processing variables, so the look stays consistent across weather and time of day.
# postfx_desaturation is 1.0 in every vanilla weather keyframe and behaves like a saturation
# multiplier (below 1 = less colour) - semantics UNVERIFIED, check in game.
LOOKS = {
    'warm': {
        'postfx_correct_col_r': 1.05, 'postfx_correct_col_g': 1.01, 'postfx_correct_col_b': 0.92,
        'postfx_desaturation': 1.08,
    },
    'cool': {
        'postfx_correct_col_r': 0.95, 'postfx_correct_col_g': 0.99, 'postfx_correct_col_b': 1.07,
        'postfx_desaturation': 0.97,
    },
    'cinematic': {
        'postfx_correct_col_r': 1.02, 'postfx_correct_col_g': 1.00, 'postfx_correct_col_b': 0.97,
        'postfx_desaturation': 0.93,
        'postfx_vignetting_intensity': 0.30,
    },
    'realistic': {
        'postfx_desaturation': 0.95,
        'lens_artefacts_intensity': 0.0,
        'chrom_aberration_coeff': 0.0,
    },
}

# Performance tiers: only variables that change rendering cost. Rules of thumb - measure FPS.
TIERS = {
    'low': {'shadow_distance_mult': 0.75, 'lod_mult': 0.85, 'dof_enable_hq': 0.0},
    'medium': {'dof_enable_hq': 0.0},
    'high': {},
}


def modifier_xml(name, values):
    lines = [f'  <modifier name="{name}" numMods="{len(values)}" userFlags="0">']
    for var, v in values.items():
        lines.append(f'    <{var}>{v:.3f} 0.000</{var}>')
    lines.append('  </modifier>')
    return '\n'.join(lines)


CLIENT_LUA = r'''-- Generated by make_timecycle_pack.py. Applies the chosen look in the EXTRA timecycle slot,
-- so scripts that use SetTimecycleModifier (cameras, drugs, interiors) keep working.
local PACK = '%(name)s'
local LOOKS = { %(looks)s }
local TIERS = { %(tiers)s }
local DEFAULT_LOOK, DEFAULT_TIER = '%(default_look)s', '%(default_tier)s'

local function modifierName(look, tier)
    if #TIERS == 0 then return ('%%s_%%s'):format(PACK, look) end
    return ('%%s_%%s_%%s'):format(PACK, look, tier)
end

local function contains(list, value)
    for _, v in ipairs(list) do if v == value then return true end end
    return false
end

local function apply()
    local look = GetResourceKvpString('look') or DEFAULT_LOOK
    local tier = GetResourceKvpString('tier') or DEFAULT_TIER
    if look == 'off' then
        ClearExtraTimecycleModifier()
        return
    end
    if not contains(LOOKS, look) then look = DEFAULT_LOOK end
    if #TIERS > 0 and not contains(TIERS, tier) then tier = DEFAULT_TIER end
    SetExtraTimecycleModifier(modifierName(look, tier))
end

RegisterCommand('graphics', function(_, args)
    local look, tier = args[1], args[2]
    if not look then
        print(('usage: /graphics <%%s|off> [%%s]'):format(table.concat(LOOKS, '|'), table.concat(TIERS, '|')))
        return
    end
    if look ~= 'off' and not contains(LOOKS, look) then return print('unknown look: ' .. look) end
    SetResourceKvp('look', look)
    if tier then
        if not contains(TIERS, tier) then return print('unknown tier: ' .. tier) end
        SetResourceKvp('tier', tier)
    end
    apply()
end, false)

AddEventHandler('onClientResourceStart', function(res)
    if res == GetCurrentResourceName() then apply() end
end)

AddEventHandler('onResourceStop', function(res)
    if res == GetCurrentResourceName() then ClearExtraTimecycleModifier() end
end)
'''


def main():
    ap = argparse.ArgumentParser(description='Generate a timecycle graphics pack resource')
    ap.add_argument('--name', required=True, help='unique lowercase prefix, e.g. dio_gfx (avoid vanilla names)')
    ap.add_argument('--looks', default=','.join(LOOKS), help='comma list from: ' + ', '.join(LOOKS))
    ap.add_argument('--default', default=None, help='default look')
    ap.add_argument('--no-tiers', action='store_true', help='one modifier per look, no low/medium/high')
    ap.add_argument('--default-tier', default='high')
    ap.add_argument('-o', '--out', required=True)
    args = ap.parse_args()

    name = args.name.strip().lower()
    if not name.replace('_', '').isalnum():
        raise SystemExit('--name must be letters, digits and underscores')
    looks = [l.strip() for l in args.looks.split(',') if l.strip()]
    unknown = [l for l in looks if l not in LOOKS]
    if unknown:
        raise SystemExit(f'unknown looks: {unknown}; choose from {list(LOOKS)}')
    default_look = args.default or looks[0]
    tiers = [] if args.no_tiers else list(TIERS)

    mods = []
    for look in looks:
        if tiers:
            for tier in tiers:
                values = dict(LOOKS[look]); values.update(TIERS[tier])
                mods.append(modifier_xml(f'{name}_{look}_{tier}', values))
        else:
            mods.append(modifier_xml(f'{name}_{look}', LOOKS[look]))

    os.makedirs(os.path.join(args.out, 'data'), exist_ok=True)
    xml_name = f'timecycle_mods_{name}.xml'
    with open(os.path.join(args.out, 'data', xml_name), 'w', encoding='utf-8') as fh:
        fh.write('<?xml version="1.0" encoding="UTF-8"?>\n<timecycle_modifier_data version="1.000000">\n')
        fh.write('\n'.join(mods) + '\n</timecycle_modifier_data>\n')
    with open(os.path.join(args.out, 'fxmanifest.lua'), 'w', encoding='utf-8') as fh:
        fh.write(f"""fx_version 'cerulean'
game 'gta5'
lua54 'yes'

description '{name} graphics pack (timecycle modifiers)'

files {{
  'data/{xml_name}',
}}

data_file 'TIMECYCLEMOD_FILE' 'data/{xml_name}'

client_script 'client.lua'
""")
    q = lambda xs: ', '.join(f"'{x}'" for x in xs)
    with open(os.path.join(args.out, 'client.lua'), 'w', encoding='utf-8') as fh:
        fh.write(CLIENT_LUA % dict(name=name, looks=q(looks), tiers=q(tiers), default_look=default_look,
                                   default_tier=args.default_tier if tiers else ''))
    with open(os.path.join(args.out, 'README.md'), 'w', encoding='utf-8') as fh:
        fh.write(f"""# {name}

Server-side graphics pack: every player gets it automatically, no client install.

- Install: put this folder in `resources/`, add `ensure {os.path.basename(os.path.abspath(args.out))}` to server.cfg.
- Players: `/graphics <{'|'.join(looks)}|off>{' [' + '|'.join(tiers) + ']' if tiers else ''}` — the choice is saved per player.
- Tune: on a dev server with `sv_pureLevel 0`, open FiveM's TimeCycle Editor, clone a modifier, adjust, "Generate XML", paste into `data/{xml_name}` (keep `numMods` equal to the number of variables).
- Values are starting points, not measured standards.
""")
    print(f'wrote resource to {args.out}: {len(mods)} modifiers ({", ".join(looks)}{"; tiers " + ", ".join(tiers) if tiers else ""})')


if __name__ == '__main__':
    main()
